### ISSUE TITLE
VALOR2

### ISSUE THREAD

**Issue by wdecoster** [BilkentCompGen/valor#9]
Is this also the repository for VALOR2? I can't find another repository it seems, and here nothing refers to VALOR**2**. It is possible that I missed it, but I also didn't spot a URL in the Genome Biology article.

Thanks,
Wouter

**Comment by calkan** [comment]
yes it is. The old version (v1) is not really usable any more, and archived in rasekh-etal directory. We will add a note to this in README.

**Comment by wdecoster** [comment]
Thanks!
